#!/bin/bash

# Path to your colors.sh file generated by pywal
COLORS_FILE="$HOME/.cache/wal/colors.sh"
# Path to your CSS file
CSS_FILE="$HOME/.config/wofi/style.css"

# Source the colors.sh file
source $COLORS_FILE

# Replace placeholders in CSS file with the colors from pywal
sed -i "s/--color1/${color1}/g" $CSS_FILE
sed -i "s/--color2/${color2}/g" $CSS_FILE
sed -i "s/--color3/${color3}/g" $CSS_FILE
sed -i "s/--color4/${color4}/g" $CSS_FILE
sed -i "s/--color5/${color5}/g" $CSS_FILE
sed -i "s/--color6/${color6}/g" $CSS_FILE
sed -i "s/--color7/${color7}/g" $CSS_FILE
sed -i "s/--color8/${color8}/g" $CSS_FILE

